### ISSUE TITLE
ЧПУ

### ISSUE THREAD

**Issue by annaSchugay** [annaSchugay/yiiblog#15]
Сделать роуты для просмотра статьи и категории через слаг
поправить:
контроллер: добавить метод findModelBySlug($slug)
контроллер: изменить actionView($id) -> actionView($slug) и поправить в нем соответствующие мет оды
view: изменить ссылки с $id на $slug в шаблонах

**Comment by aivavic** [comment]
We need to adjust controller. Add the following method:

```
protected function findModelBySlug($slug)
{
    if (($model = Post::findOne(['slug' => $slug])) !== null) {
        return $model;
    } else {
        throw new NotFoundHttpException();
    }
}
```

Now adjust view action:

```
public function actionView($slug)
{
    return $this->render('view', [
        'model' => $this->findModelBySlug($slug),
    ]);
}
```

**Comment by aivavic** [comment]
вот тут дока по ActionColumns для GridView
https://www.yiiframework.com/doc/api/2.0/yii-grid-actioncolumn
вот тут примеры хорошие
http://www.bsourcecode.com/yiiframework2/gridview-in-yiiframework-2-0/
